require("user.vimwiki")
require("user.options").load_defaults()
require("user.lazy")
require("user.plugconf")
require("user.LSP")
-- require("user.DAP")
require("user.Formatter")
require("user.keymap")
require("user.color")
require("user.autocmd")
