require("user.plugconf.telescope")
require("user.plugconf.bufferline")
require("user.plugconf.blankline")
require("user.plugconf.lualine")
require("user.plugconf.vimtex")
require("user.plugconf.comment")
require("user.plugconf.notify")
--require("user.plugconf.vimspector")
require("user.plugconf.markdown-preview")
require("user.plugconf.which-key")
-- require("user.plugconf.aerial")
-- require("which-key").setup()
